name: Release app
on:
  workflow_dispatch:
  
jobs:
  build:
    strategy:
      matrix:
        os:
          [
            { name: 'windows', image: 'windows-latest' },
            { name: 'macos-arm', image: 'macos-latest' },
            { name: 'macos-x86', image: 'macos-13' }
          ]
    runs-on: ${{ matrix.os.image }}
    steps:
      - name: Github checkout
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm ci
        env:
          VITE_CLOUDANT_URL: ${{ secrets.VITE_CLOUDANT_URL }}
          VITE_CLOUDANT_USERNAME: ${{ secrets.VITE_CLOUDANT_USERNAME }}
          VITE_CLOUDANT_PASSWORD: ${{ secrets.VITE_CLOUDANT_PASSWORD }}
          VITE_AUTH0_DOMAIN: ${{ secrets.VITE_AUTH0_DOMAIN }}
          VITE_AUTH0_CLIENT_ID: ${{ secrets.VITE_AUTH0_CLIENT_ID }}
      - name: Package app
        env:
          VITE_CLOUDANT_URL: ${{ secrets.VITE_CLOUDANT_URL }}
          VITE_CLOUDANT_USERNAME: ${{ secrets.VITE_CLOUDANT_USERNAME }}
          VITE_CLOUDANT_PASSWORD: ${{ secrets.VITE_CLOUDANT_PASSWORD }}
          VITE_AUTH0_DOMAIN: ${{ secrets.VITE_AUTH0_DOMAIN }}
          VITE_AUTH0_CLIENT_ID: ${{ secrets.VITE_AUTH0_CLIENT_ID }}
        run: npm run package
      - name: Make app
        env:
          VITE_CLOUDANT_URL: ${{ secrets.VITE_CLOUDANT_URL }}
          VITE_CLOUDANT_USERNAME: ${{ secrets.VITE_CLOUDANT_USERNAME }}
          VITE_CLOUDANT_PASSWORD: ${{ secrets.VITE_CLOUDANT_PASSWORD }}
          VITE_AUTH0_DOMAIN: ${{ secrets.VITE_AUTH0_DOMAIN }}
          VITE_AUTH0_CLIENT_ID: ${{ secrets.VITE_AUTH0_CLIENT_ID }}
        run: npm run make
      - name: Publish app
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          VITE_CLOUDANT_URL: ${{ secrets.VITE_CLOUDANT_URL }}
          VITE_CLOUDANT_USERNAME: ${{ secrets.VITE_CLOUDANT_USERNAME }}
          VITE_CLOUDANT_PASSWORD: ${{ secrets.VITE_CLOUDANT_PASSWORD }}
          VITE_AUTH0_DOMAIN: ${{ secrets.VITE_AUTH0_DOMAIN }}
          VITE_AUTH0_CLIENT_ID: ${{ secrets.VITE_AUTH0_CLIENT_ID }}
        run: npm run publish
